services:
  - type: web
    name: yt-dlp-api
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: PORT
        value: 10000
